[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/MapleChat-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/swagger-ui.html"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
